// Mock Data
import type { CaseFile, KycRecord, Regulation, Transaction } from "@/lib/types";

export const mockKyc: KycRecord[] = [
  {
    account_id: "ACC-8891",
    customer_name: "Meridian Capital Group",
    entity_type: "corporate",
    country_of_incorporation: "CY",
    risk_score: 78,
    risk_level: "high",
    onboarding_date: "2025-08-12",
    last_review_date: "2026-01-15",
    pep_status: false,
    sanctions_match: false,
    document_status: "incomplete",
    beneficial_owners: ["John Doe", "Jane Smith"],
    industry: "financial_services",
  },
  {
    account_id: "ACC-7702",
    customer_name: "Pacific Import Export",
    entity_type: "corporate",
    country_of_incorporation: "AE",
    risk_score: 71,
    risk_level: "high",
    onboarding_date: "2025-03-04",
    last_review_date: "2025-12-01",
    pep_status: false,
    sanctions_match: false,
    document_status: "complete",
    beneficial_owners: ["Omar Haddad"],
    industry: "import_export",
  },
  {
    account_id: "ACC-5310",
    customer_name: "Riviera Property SC",
    entity_type: "corporate",
    country_of_incorporation: "SC",
    risk_score: 64,
    risk_level: "medium",
    onboarding_date: "2025-06-20",
    last_review_date: "2026-02-10",
    pep_status: true,
    sanctions_match: false,
    document_status: "complete",
    beneficial_owners: ["Elena Petrova", "Marco Rossi"],
    industry: "real_estate",
  },
];

export const mockTransactions: Transaction[] = [
  {
    transaction_id: "TXN-2026-000412",
    timestamp: "2026-05-15T09:14:00Z",
    amount: 21450.0,
    currency: "USD",
    type: "wire_transfer",
    direction: "outbound",
    account_id: "ACC-8891",
    counterparty: "Aurora Holdings Ltd",
    counterparty_country: "CY",
    description: "Investment advisory fee",
    risk_flags: ["high_amount", "cross_border", "rapid_succession"],
    status: "completed",
  },
  {
    transaction_id: "TXN-2026-000418",
    timestamp: "2026-05-15T10:02:00Z",
    amount: 19875.5,
    currency: "USD",
    type: "wire_transfer",
    direction: "outbound",
    account_id: "ACC-8891",
    counterparty: "Aurora Holdings Ltd",
    counterparty_country: "CY",
    description: "Investment advisory fee",
    risk_flags: ["high_amount", "cross_border", "rapid_succession"],
    status: "completed",
  },
  {
    transaction_id: "TXN-2026-000425",
    timestamp: "2026-05-15T11:47:00Z",
    amount: 23110.0,
    currency: "USD",
    type: "wire_transfer",
    direction: "outbound",
    account_id: "ACC-8891",
    counterparty: "Aurora Holdings Ltd",
    counterparty_country: "CY",
    description: "Investment advisory fee",
    risk_flags: ["high_amount", "cross_border", "rapid_succession"],
    status: "completed",
  },
  {
    transaction_id: "TXN-2026-000771",
    timestamp: "2026-06-03T10:18:00Z",
    amount: 20500.0,
    currency: "USD",
    type: "wire_transfer",
    direction: "outbound",
    account_id: "ACC-8891",
    counterparty: "Aurora Holdings Ltd",
    counterparty_country: "CY",
    description: "Advisory retainer",
    risk_flags: ["high_amount", "cross_border", "rapid_succession"],
    status: "completed",
  },
  {
    transaction_id: "TXN-2026-000088",
    timestamp: "2026-04-22T14:05:00Z",
    amount: 3200.0,
    currency: "USD",
    type: "ach",
    direction: "outbound",
    account_id: "ACC-8891",
    counterparty: "City Utilities Co",
    counterparty_country: "US",
    description: "Service fee",
    risk_flags: [],
    status: "completed",
  },
];

export const mockRegulations: Regulation[] = [
  {
    regulation_id: "REG-BSA-SAR-001",
    title: "Bank Secrecy Act - Suspicious Activity Reporting (SAR)",
    body: "Financial institutions must file a Suspicious Activity Report with FinCEN when they detect a transaction involving at least 5,000 US dollars that they know, suspect, or have reason to suspect involves funds from illegal activity, is structured to evade reporting requirements, or has no apparent lawful purpose.",
    jurisdiction: "US",
    authority: "FinCEN",
    effective_date: "2024-01-01",
    last_updated: "2025-06-15",
    categories: ["AML", "SAR", "reporting"],
  },
  {
    regulation_id: "REG-CROSSBORDER-005",
    title: "Cross-Border Funds Transfer Scrutiny",
    body: "Cross-border wire transfers, particularly to jurisdictions identified as higher risk for money laundering, warrant heightened scrutiny. Rapid sequences of cross-border transfers may indicate layering.",
    jurisdiction: "US",
    authority: "FinCEN",
    effective_date: "2024-01-01",
    last_updated: "2025-05-01",
    categories: ["AML", "cross_border", "wire_transfer"],
  },
  {
    regulation_id: "REG-CTR-002",
    title: "Currency Transaction Reporting - $10,000 Threshold",
    body: "A Currency Transaction Report must be filed for any cash transaction, or series of related cash transactions in a single business day, that exceeds 10,000 US dollars. Breaking a large amount into smaller transactions to stay under this threshold is structuring, a federal crime.",
    jurisdiction: "US",
    authority: "FinCEN",
    effective_date: "2024-01-01",
    last_updated: "2025-03-10",
    categories: ["AML", "CTR", "reporting", "structuring"],
  },
];

export const mockCaseFiles: CaseFile[] = [
  {
    case_id: "CASE-2026-0007",
    created_at: "2026-03-18T09:30:00Z",
    created_by: "vigil-agent",
    subject: "Pacific Import Export - Round-number cash deposits",
    summary:
      "Series of round-number deposits just below the $10,000 reporting threshold over a two-week period on ACC-7702. Pattern consistent with possible structuring. Enhanced monitoring applied.",
    entities_involved: ["ACC-7702", "Pacific Import Export"],
    risk_level: "high",
    status: "open",
    findings: [
      "Multiple deposits between $9,200 and $9,800",
      "Deposits across several branches in a short window",
      "Possible structuring to evade CTR threshold",
    ],
    recommended_actions: ["Enhanced monitoring on ACC-7702", "Consider SAR if pattern continues"],
    related_cases: [],
  },
  {
    case_id: "CASE-2026-0019",
    created_at: "2026-05-02T11:10:00Z",
    created_by: "vigil-agent",
    subject: "Riviera Property SC - PEP real-estate inflows",
    summary:
      "Large inbound transfers to ACC-5310, whose beneficial owner is a Politically Exposed Person. Enhanced due diligence triggered; escalated to senior compliance for source-of-funds review.",
    entities_involved: ["ACC-5310", "Riviera Property SC"],
    risk_level: "medium",
    status: "escalated",
    findings: ["Beneficial owner flagged as PEP", "Inbound funds inconsistent with stated business"],
    recommended_actions: ["Obtain source-of-funds documentation", "Senior management sign-off"],
    related_cases: [],
  },
  {
    case_id: "CASE-2026-0011",
    created_at: "2026-04-02T14:05:00Z",
    created_by: "vigil-agent",
    subject: "Summit Ventures Ltd - Resolved false positive",
    summary:
      "Velocity alert on ACC-3300 reviewed and cleared. Spike corresponded to a documented, legitimate quarterly supplier settlement. No further action.",
    entities_involved: ["ACC-3300", "Summit Ventures Ltd"],
    risk_level: "low",
    status: "resolved",
    findings: ["Velocity spike explained by quarterly supplier payments", "Supporting invoices on file"],
    recommended_actions: ["Close alert", "No SAR required"],
    related_cases: [],
  },
];
